services:
  minio:
    image: minio_batch
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
      - MINIO_PROMETHEUS_AUTH_TYPE=public
    volumes:
      - minio_data:/data
    networks:
      - airflow
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    
  grafana:
    image: grafana_batch
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    networks:
      - airflow
    restart: always
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana 

  trino:
    image: trino_batch
    container_name: trino
    ports:
      - "8082:8080" 
    volumes:
      - ./docker/trino/catalog:/etc/trino/catalog 
      - ./docker/trino/init-tables.sql:/etc/trino/init-tables.sql
    depends_on:
      - minio
    networks:
      - airflow
    restart: always
  
  prometheus:
    image: prometheus_batch
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - airflow
    restart: always

  statsd-exporter:
    image: statsd-exporter 
    container_name: statsd-exporter
    ports:
      - "9102:9102" 
      - "9125:9125"
    volumes:
      - ./docker/statsd/mappings.yml:/tmp/mappings.yml
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9102/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    command:
      - '--statsd.mapping-config=/tmp/mappings.yml'
      - '--statsd.listen-udp=:9125'
      - '--web.listen-address=:9102'
    restart: always
    networks:
      - airflow

  marquez:
    image: marquezproject/marquez
    container_name: marquez
    environment:
      - MARQUEZ_PORT=5000
      - MARQUEZ_ADMIN_PORT=5001
      - POSTGRES_HOST=batch-pipeline_b89794-postgres-1
      - POSTGRES_PORT=5432
      - POSTGRES_DB=marquez
      - POSTGRES_USER=marquez
      - POSTGRES_PASSWORD=marquez
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - airflow
    restart: always

  marquez-web:
    image: marquezproject/marquez-web
    container_name: marquez-web
    environment:
      - MARQUEZ_HOST=marquez
      - MARQUEZ_PORT=5000
      - WEB_PORT=3000
    ports:
      - "3001:3000"
    depends_on:
      - marquez
    networks:
      - airflow
    restart: always


volumes:
  minio_data:
  grafana-storage: 
  marquez-data:
  
